export enum Vendors {
  USHA = "USHA",
  WAAH_HYDERABADI = "WAAH_HYDERABADI",
  ANANDA = "ANANDA",
  COOLBIZ = "COOLBIZ",
  CHATCORNER = "CHATCORNER",
  CHAIWALA = "CHAIWALA",
  ZAITOON = "ZAITOON",
  NARMADA_XEROX = "NARMADA_XEROX",
  SEVEN_STAR_SALON = "SEVEN_STAR_SALON",
  MOOSHA = "MOOSHA",
}

export enum Messes {
  SRR = "SRR",
  SGR = "SGR",
  NEELKESH = "NEELKESH",
  FIRSTMAN = "FIRSTMAN",
  VINDYA = "VINDYA",
}
